// Dados mockados centralizados para tours, restaurantes e acomodações

export const MOCK_TOURS = [
  {
    id: 1,
    title: 'Passeio de Barco na Lagoa',
    location: 'Barra de São Miguel',
    rating: 4.8,
    duration: '3h',
    price: 'R$ 120',
    image: '/images/browse-1.jpg',
    people: 10,
    description: 'Explore as belezas naturais da lagoa com guia local e paradas para banho.'
  },
  {
    id: 2,
    title: 'Trilha Ecológica',
    location: 'Barra de São Miguel',
    rating: 4.6,
    duration: '2h',
    price: 'R$ 80',
    image: '/images/browse-2.jpg',
    people: 15,
    description: 'Caminhada guiada por trilhas ecológicas, com observação de fauna e flora.'
  },
  {
    id: 3,
    title: 'Passeio de Buggy',
    location: 'Praia do Gunga',
    rating: 4.9,
    duration: '4h',
    price: 'R$ 200',
    image: '/images/browse-3.jpg',
    people: 4,
    description: 'Aventura pelas dunas e praias paradisíacas com buggy.'
  },
  {
    id: 4,
    title: 'Mergulho com Cilindro',
    location: 'Barra de São Miguel',
    rating: 4.7,
    duration: '1h',
    price: 'R$ 250',
    image: '/images/browse-4.jpg',
    people: 2,
    description: 'Experiência de mergulho para iniciantes e avançados, com instrutor.'
  },
  {
    id: 5,
    title: 'Passeio de Stand Up Paddle',
    location: 'Praia do Francês',
    rating: 4.5,
    duration: '1.5h',
    price: 'R$ 70',
    image: '/images/browse-5.jpg',
    people: 6,
    description: 'Remada tranquila pelas águas calmas, ideal para todas as idades.'
  },
  {
    id: 6,
    title: 'Observação de Aves',
    location: 'Amazônia',
    rating: 5.0,
    duration: '3 dias',
    price: 'R$ 549,00',
    image: '/images/browse-1.jpg',
    people: 2,
    description: 'Tour guiado para observação de aves raras na floresta amazônica.'
  },
  {
    id: 7,
    title: 'Experiência com comunidade indígena',
    location: 'Haliti-Paresí',
    rating: 5.0,
    duration: '3 dias',
    price: 'R$ 649,00',
    image: '/images/browse-2.jpg',
    people: 2,
    description: 'Vivência cultural e imersão em comunidade indígena.'
  },
  {
    id: 8,
    title: 'Passeio de barco - rio Paraguai',
    location: 'Pantanal',
    rating: 5.0,
    duration: '3 dias',
    price: 'R$ 349,00',
    image: '/images/browse-3.jpg',
    people: 2,
    description: 'Navegação pelo rio Paraguai com observação de fauna e flora.'
  },
  {
    id: 9,
    title: 'Caminhada noturna',
    location: 'Chapada dos Guimarães',
    rating: 4.8,
    duration: '2h',
    price: 'R$ 90',
    image: '/images/browse-4.jpg',
    people: 8,
    description: 'Trilha guiada à noite para observação de animais silvestres.'
  },
  {
    id: 10,
    title: 'Safari fotográfico',
    location: 'Pantanal',
    rating: 4.9,
    duration: '5h',
    price: 'R$ 300',
    image: '/images/browse-5.jpg',
    people: 12,
    description: 'Passeio para fotografar a fauna exuberante do Pantanal.'
  },
];

export const MOCK_RESTAURANTS = [
  {
    id: 1,
    title: 'Pantanal Grill',
    location: 'Pantanal',
    rating: 4.9,
    duration: 'Special Menu',
    price: 'R$99.00',
    image: '/images/category-1.jpg',
    description: 'Pantanal Grill',
    people: 2,
  },
  {
    id: 2,
    title: 'Amazon Bistro',
    location: 'Amazon',
    rating: 4.8,
    duration: 'Special Menu',
    price: 'R$129.00',
    image: '/images/category-2.jpg',
    description: 'Amazon Bistro',
    people: 2,
  },
  {
    id: 3,
    title: 'Amazon Bistro',
    location: 'Amazon',
    rating: 4.8,
    duration: 'Special Menu',
    price: 'R$129.00',
    image: '/images/category-2.jpg',
    description: 'Amazon Bistro',
    people: 2,
  },
  {
    id: 4,
    title: 'Amazon Bistro2',
    location: 'Amazon',
    rating: 4.8,
    duration: 'Special Menu',
    price: 'R$129.00',
    image: '/images/category-2.jpg',
    description: 'Amazon Bistro',
    people: 2,
  },
  {
    id: 5,
    title: 'Amazon Bistro3',
    location: 'Amazon',
    rating: 4.8,
    duration: 'Special Menu',
    price: 'R$129.00',
    image: '/images/category-2.jpg',
    description: 'Amazon Bistro',
    people: 2,
  },
];

export const MOCK_ACCOMMODATIONS = [
  {
    id: 1,
    title: 'Eco Resort',
    location: 'Chapada',
    rating: 4.8,
    duration: '2 nights',
    price: 'R$799.00',
    image: '/images/browse-4.jpg',
    description: 'Eco Resort',
    people: 2,
  },
  {
    id: 2,
    title: 'Boutique Hotel',
    location: 'Cuiabá',
    rating: 4.7,
    duration: '1 night',
    price: 'R$499.00',
    image: '/images/browse-5.jpg',
    description: 'Boutique Hotel',
    people: 2,
  },
  {
    id: 3,
    title: 'Pousada Pantanal Encantado',
    location: 'Pantanal',
    rating: 4.9,
    duration: '3 nights',
    price: 'R$1200.00',
    image: '/images/category-1.jpg',
    description: 'Pousada com vista para o Pantanal, piscina e café da manhã incluso.',
    people: 4,
  },
  {
    id: 4,
    title: 'Hotel Beira Rio',
    location: 'Beira Rio',
    rating: 4.6,
    duration: '2 nights',
    price: 'R$700.00',
    image: '/images/category-2.jpg',
    description: 'Hotel com vista para o rio, quartos confortáveis e restaurante próprio.',
    people: 3,
  },
  {
    id: 5,
    title: 'Resort Paraíso das Águas',
    location: 'Praia',
    rating: 4.8,
    duration: '4 nights',
    price: 'R$2000.00',
    image: '/images/category-3.jpg',
    description: 'Resort completo com lazer, spa, piscinas e restaurante.',
    people: 5,
  },
  {
    id: 6,
    title: 'Hostel Trilha Jovem',
    location: 'Centro',
    rating: 4.5,
    duration: '1 night',
    price: 'R$80.00',
    image: '/images/category-4.jpg',
    description: 'Opção econômica, ambiente jovem e descontraído.',
    people: 1,
  },
  {
    id: 7,
    title: 'Pousada Vida Verde',
    location: 'Centro',
    rating: 4.7,
    duration: '2 nights',
    price: 'R$300.00',
    image: '/images/category-5.jpg',
    description: 'Ambiente familiar, café da manhã e estacionamento.',
    people: 2,
  },
]; 